# Generated by Django 4.2.4 on 2023-09-06 00:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenido", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("titulo", models.CharField(max_length=255, verbose_name="Título")),
                ("alias", models.CharField(max_length=255, verbose_name="Alias")),
                ("esModerada", models.BooleanField(default=False, verbose_name="¿Es moderada?")),
            ],
        ),
    ]
