# Generated by Django 4.2.4 on 2023-09-06 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("contenido", "0002_categoria"),
    ]

    operations = [
        migrations.AddField(
            model_name="contenido",
            name="categoria",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categoria",
                to="contenido.categoria",
            ),
            preserve_default=False,
        ),
    ]
