# Generated by Django 4.2.4 on 2023-09-07 22:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import tinymce.models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contenido", "0003_contenido_categoria"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categoria",
            name="alias",
            field=models.CharField(
                blank=True,
                help_text="Ejemplo: 'Ingeniería de Software II' -> 'is2'",
                max_length=255,
                verbose_name="Alias",
            ),
        ),
        migrations.AlterField(
            model_name="contenido",
            name="fechaVencimiento",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Fecha de vencimiento"),
        ),
        migrations.CreateModel(
            name="HistoricalContenido",
            fields=[
                ("id", models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID")),
                ("titulo", models.CharField(max_length=255, verbose_name="Título")),
                ("contenido", tinymce.models.HTMLField(verbose_name="Descripción del contenido")),
                ("fechaCreacion", models.DateTimeField(blank=True, editable=False, verbose_name="Fecha de creación")),
                ("fechaVencimiento", models.DateTimeField(blank=True, null=True, verbose_name="Fecha de vencimiento")),
                ("esPublico", models.BooleanField(default=True, verbose_name="¿Es público?")),
                (
                    "estado",
                    models.IntegerField(
                        choices=[
                            (1, "Borrador"),
                            (2, "Revisión"),
                            (3, "A publicar"),
                            (4, "Publicado"),
                            (5, "Rechazado"),
                            (6, "Inactivo"),
                        ],
                        default=1,
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "autor",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="contenido.categoria",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical contenido",
                "verbose_name_plural": "historical contenidos",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalCategoria",
            fields=[
                ("id", models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID")),
                ("titulo", models.CharField(max_length=255, verbose_name="Título")),
                (
                    "alias",
                    models.CharField(
                        blank=True,
                        help_text="Ejemplo: 'Ingeniería de Software II' -> 'is2'",
                        max_length=255,
                        verbose_name="Alias",
                    ),
                ),
                ("esModerada", models.BooleanField(default=False, verbose_name="¿Es moderada?")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical categoria",
                "verbose_name_plural": "historical categorias",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
