# Generated by Django 4.2.4 on 2023-09-14 00:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenido", "0004_alter_categoria_alias_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="categoria",
            name="activo",
            field=models.BooleanField(default=True, verbose_name="¿Está activo?"),
        ),
        migrations.AddField(
            model_name="contenido",
            name="activo",
            field=models.BooleanField(default=True, verbose_name="¿Está activo?"),
        ),
        migrations.AddField(
            model_name="historicalcategoria",
            name="activo",
            field=models.BooleanField(default=True, verbose_name="¿Está activo?"),
        ),
        migrations.AddField(
            model_name="historicalcontenido",
            name="activo",
            field=models.BooleanField(default=True, verbose_name="¿Está activo?"),
        ),
        migrations.AlterField(
            model_name="contenido",
            name="estado",
            field=models.IntegerField(
                choices=[(1, "Borrador"), (2, "Revisión"), (3, "A publicar"), (4, "Publicado"), (5, "Rechazado")],
                default=1,
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontenido",
            name="estado",
            field=models.IntegerField(
                choices=[(1, "Borrador"), (2, "Revisión"), (3, "A publicar"), (4, "Publicado"), (5, "Rechazado")],
                default=1,
            ),
        ),
    ]
