# Generated by Django 4.2.4 on 2023-09-30 16:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contenido", "0005_categoria_activo_contenido_activo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="categoria",
            name="autores_permitidos",
            field=models.ManyToManyField(related_name="categorias_autorizadas", to=settings.AUTH_USER_MODEL),
        ),
    ]
