# Generated by Django 4.2.4 on 2023-10-01 12:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenido", "0006_categoria_autores_permitidos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categoria",
            name="esModerada",
            field=models.BooleanField(default=True, verbose_name="¿Es moderada?"),
        ),
        migrations.AlterField(
            model_name="historicalcategoria",
            name="esModerada",
            field=models.BooleanField(default=True, verbose_name="¿Es moderada?"),
        ),
    ]
