# Generated by Django 4.2.4 on 2023-10-06 11:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenido", "0008_contenido_editor_contenido_publicador_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalcontenido",
            name="history_change_reason",
            field=models.TextField(null=True),
        ),
    ]
