# Generated by Django 4.2.4 on 2023-10-17 10:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenido", "0009_alter_historicalcontenido_history_change_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="contenido",
            name="change_reason",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="historicalcontenido",
            name="change_reason",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
