# Generated by Django 4.2.4 on 2023-10-17 10:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenido", "0010_contenido_change_reason_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contenido",
            name="change_reason",
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Agregar comentario"),
        ),
        migrations.AlterField(
            model_name="historicalcontenido",
            name="change_reason",
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Agregar comentario"),
        ),
    ]
