# Generated by Django 4.2.4 on 2023-10-20 14:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contenido", "0012_contenido_resumen_historicalcontenido_resumen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categoria",
            name="autores_permitidos",
            field=models.ManyToManyField(
                blank=True, related_name="categorias_autorizadas", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
